version: '3.8'

services:
  db:
    image: postgres:16
    container_name: ctapp-postgres
    restart: always
    environment:
      POSTGRES_USER: ctapp_user
      POSTGRES_PASSWORD: ctapp_password
      POSTGRES_DB: ctapp_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: